@startuml
'https://plantuml.com/object-diagram
package "Code Review"{
    object "pull_requests" as pull_requests
    object "pull_request_commits" as pull_request_commits
    object "pull_request_comments" as pull_request_comments
}
@enduml
