@startuml
'https://plantuml.com/object-diagram
!$varchar255 = "varchar(255)"

package CI/CD {
    object "cicd_scopes" as cicd_scopes{
        id = $varchar255
    }

    object "cicd_pipelines" as cicd_pipelines{
        id = $varchar255
    }
'    cicd_scopes::id <-- cicd_pipelines::id

    object "cicd_tasks" as cicd_tasks
    object "cicd_pipeline_commits" as cicd_pipeline_commits
    object "cicd_deployments" as cicd_deployments
    object "cicd_deployment_commits" as cicd_deployment_commits{
        environment = varchar255
    }

}


@enduml
