@startuml
'https://plantuml.com/object-diagram
allowmixing
'!theme cyborg
'!theme sandstone
package Demo{
    package APILayer {

    }

    package RawLayer {

    }

    package ToolLayer {

    }

    package DomainLayer {
        !include domain.puml
    }
}
@enduml
